name: Vecel Preview Deploy
env: 
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
on: 
  push:
    branches-ignore:
        - master

jobs:
  Deploy-Production:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v4

        - name: Install Vercel CLI
          run: npm install --global vercel

        - name: Pull Vercel Environment Information
          run: vercel pull --yes environment=production --token=${{secrets.VERCEL_TOKEN}}

        - name: Build Project React Template
          run: vercel build  --token=${{secrets.VERCEL_TOKEN}}
        
        - name: Deploy Project React Template
          run: vercel deploy --prebuild --token=${{secrets.VERCEL_TOKEN}}